name: CI

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

defaults:
  run:
    working-directory: ./satallite

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: satallite/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Build Docker image
        run: docker build -t satellite-api .

      - name: Run Docker container
        run: docker compose up -d

      - name: Test Docker container
        run: |
          sleep 10 # Wait for the container to start
          curl -f curl -f http://localhost:3000/satellites/25544 || exit 1